import test from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../src/app.js";
import { MemoryRepository } from "../src/repository.js";
import { MockAcceleventsClient } from "../src/accelevents.js";
import type { CompetitionSnapshot, SnapshotPersistence } from "../src/persistence.js";

const post=(app:ReturnType<typeof createApp>,path:string,body:unknown,headers:Record<string,string>={})=>app.request(path,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});

test("accepted canonical session schedules, publishes only eligible speakers, and reaches sync preview",async()=>{
 const repo=new MemoryRepository(), app=createApp({repo,client:new MockAcceleventsClient()});
 const created=await post(app,"/api/public/events/ai-engineer-summit/submissions",{name:"Canonical Person",email:"canonical@example.test",answers:{title:"Canonical Talk",abstract:"A canonical test session",category:"AI Engineering",format:"Talk (30 min)",experience:"Advanced"}});
 const submission=await created.json(); const id=submission.data.id;
 await post(app,`/api/events/evt-ai-summit-2026/submissions/${id}/decision`,{nextStatus:"accepted"},{"x-demo-role":"organizer"});
 const schedule=await (await app.request("/api/events/evt-ai-summit-2026/schedule")).json(); const session=schedule.sessions.find((x:any)=>x.title==="Canonical Talk"); assert.ok(session);
 const move=await post(app,"/api/events/evt-ai-summit-2026/schedule/move",{version:schedule.version,slot:{id:"slot-canonical",sessionId:session.id,roomId:"room-community",startsAt:"2026-10-12T20:00:00.000Z",endsAt:"2026-10-12T20:45:00.000Z"},acknowledge:[]}); assert.equal(move.status,200);
 const preview=await (await post(app,"/sync/preview",{eventId:"evt-ai-summit-2026"})).json(); assert.ok(preview.items.some((x:any)=>x.localId===session.id));
 const after=await (await app.request("/api/events/evt-ai-summit-2026/schedule")).json(); const item=after.sessions.find((x:any)=>x.id===session.id); item.publishStatus="published"; item.status="published"; await repo.putSchedule("evt-ai-summit-2026",after);
 const itinerary=await (await app.request("/public/events/evt-ai-summit-2026/itinerary.json")).json(); assert.ok(itinerary.sessions.some((x:any)=>x.title==="Canonical Talk"));
 const speakers=await (await app.request("/public/events/evt-ai-summit-2026/speakers.json")).json(); assert.ok(speakers.speakers.some((x:any)=>x.name==="Canonical Person")); assert.ok(!speakers.speakers.some((x:any)=>x.name==="Grace Hopper"));
});

test("hard schedule conflict returns 409 without mutating canonical version",async()=>{const app=createApp({repo:new MemoryRepository()});const before=await (await app.request("/api/events/evt-ai-summit-2026/schedule")).json();const response=await post(app,"/api/events/evt-ai-summit-2026/schedule/move",{version:before.version,slot:{id:"blocked",sessionId:"ses-reliable-agents",roomId:"room-main",startsAt:"2026-10-12T17:00:00.000Z",endsAt:"2026-10-12T17:45:00.000Z"}});assert.equal(response.status,409);const after=await (await app.request("/api/events/evt-ai-summit-2026/schedule")).json();assert.equal(after.version,before.version);assert.equal(after.slots.length,before.slots.length)});

test("novel accepted track handoff remains canonical and schedule version is monotonic",async()=>{const repo=new MemoryRepository(),app=createApp({repo});const email=`novel-${Date.now()}@example.test`;const made=await post(app,"/api/public/events/ai-engineer-summit/submissions",{name:"Infra Person",email,answers:{title:"Taming 40-Minute CI",abstract:"CI infrastructure",category:"Platform & Infra",format:"Talk (30 min)",experience:"Advanced"}});const id=(await made.json()).data.id;await post(app,`/api/events/evt-ai-summit-2026/submissions/${id}/decision`,{nextStatus:"accepted"},{"x-demo-persona":"org-swyx"});const first=await(await app.request("/api/events/evt-ai-summit-2026/schedule")).json(),session=first.sessions.find((x:any)=>x.acceptedSubmissionId===id),track=first.tracks.find((x:any)=>session.trackIds.includes(x.id));assert.equal(track.name,"Platform & Infra");const moved=await post(app,"/api/events/evt-ai-summit-2026/schedule/move",{version:first.version,slot:{id:`slot-${id}`,sessionId:session.id,roomId:"room-main",startsAt:"2026-10-14T20:00:00.000Z",endsAt:"2026-10-14T20:45:00.000Z"}});assert.equal(moved.status,200);const v=(await moved.json()).version;for(let i=0;i<3;i++){const read=await(await app.request(`/api/events/evt-ai-summit-2026/schedule?proof=${i}`)).json();assert.equal(read.version,v);assert.ok(read.slots.some((x:any)=>x.sessionId===session.id));assert.equal(read.tracks.find((x:any)=>x.id===session.trackIds[0]).name,"Platform & Infra")}});

test("schedule placement and version survive lifecycle snapshot restoration",async()=>{let saved:CompetitionSnapshot|undefined;const persistence:SnapshotPersistence={load:async()=>saved,save:async s=>{saved=structuredClone(s)}};const repo=new MemoryRepository(),app=createApp({repo,persistence}),before=await(await app.request("/api/events/evt-ai-summit-2026/schedule")).json();const moved=await post(app,"/api/events/evt-ai-summit-2026/schedule/move",{version:before.version,slot:{id:"slot-restore-proof",sessionId:"ses-reliable-agents",roomId:"room-main",startsAt:"2026-10-14T21:00:00.000Z",endsAt:"2026-10-14T21:45:00.000Z"}});assert.equal(moved.status,200);const version=(await moved.json()).version;const restoredRepo=new MemoryRepository();const {restoreSnapshot}=await import("../src/app.js");assert.equal(await restoreSnapshot({repo:restoredRepo,persistence}),true);const after=await restoredRepo.getSchedule("evt-ai-summit-2026");assert.equal(after?.version,version);assert.ok(after?.slots.some(x=>x.id==="slot-restore-proof"))});
