import test from "node:test";
import assert from "node:assert/strict";
import { createApp,restoreSnapshot } from "../src/app.js";
import { EVENT_ID,store } from "../src/lifecycle.js";
import { addFileVersion,contentReadiness,validateUpload } from "../src/content.js";
import type { CompetitionSnapshot,SnapshotPersistence } from "../src/persistence.js";
import { MemoryRepository } from "../src/repository.js";
import { buildPublicProgram } from "../src/publicProjection.js";

const h=(id:string)=>({"content-type":"application/json","x-demo-persona":id});
const app=createApp();
test("upload validates MIME and 2MB size",()=>{assert.equal(validateUpload({mime:"application/x-msdownload",size:1,dataBase64:"eA=="}).ok,false);assert.equal(validateUpload({mime:"application/pdf",size:2*1024*1024+1,dataBase64:"eA=="}).ok,false);assert.equal(validateUpload({mime:"application/pdf",size:1,dataBase64:"eA=="},["application/pdf"]).ok,true)});
test("new upload creates current version while retaining old version",()=>{const task=store.deliverableTasks.find(t=>t.id==="deliverable-slides-ada")!,file=store.contentFiles.find(f=>f.taskId===task.id)!,before=file.versions.length;const made=addFileVersion(store,{task,name:"slides.pdf",mime:"application/pdf",size:1,dataBase64:"eA==",uploadedBy:"spk-ada",kind:"slides"});assert.equal(file.versions.length,before+1);assert.equal(made.version.current,true);assert.equal(file.versions.filter(v=>v.current).length,1)});
test("file comments roundtrip and approval transitions require organizer",async()=>{const file=store.contentFiles[0]!;const comment=await app.request(`/api/content/files/${file.id}/comments`,{method:"POST",headers:h("spk-ada"),body:JSON.stringify({body:"Speaker note"})});assert.equal(comment.status,201);assert.ok(file.comments.some(c=>c.body==="Speaker note"));const forbidden=await app.request(`/api/events/${EVENT_ID}/content/files/${file.id}/approval`,{method:"PATCH",headers:h("spk-ada"),body:JSON.stringify({status:"approved"})});assert.equal(forbidden.status,403);const approved=await app.request(`/api/events/${EVENT_ID}/content/files/${file.id}/approval`,{method:"PATCH",headers:h("org-swyx"),body:JSON.stringify({status:"approved",comment:"Ready"})});assert.equal(approved.status,200);assert.equal(file.status,"approved")});
test("speaker A cannot access speaker B file or deliverable",async()=>{const task=store.deliverableTasks.find(t=>t.speakerId==="spk-sam")!;const taskResult=await app.request(`/api/speaker/events/${EVENT_ID}/deliverables/${task.id}`,{headers:h("spk-ada")});assert.equal(taskResult.status,404);const own=store.contentFiles.find(f=>f.speakerId==="spk-ada")!,version=own.versions[0]!;const fileResult=await app.request(`/api/content/files/${own.id}/versions/${version.id}`,{headers:h("spk-sam")});assert.equal(fileResult.status,404)});
test("readiness derives completion, upload counts, and overdue",()=>{const rows=contentReadiness(store,new Date("2030-01-01"));assert.ok(rows.find(t=>t.id==="deliverable-slides-ada")!.uploadCount>=2);assert.equal(rows.find(t=>t.id==="deliverable-headshot-ada")!.overdue,true);assert.equal(rows.find(t=>t.id==="deliverable-slides-ada")!.overdue,false)});
test("session and speaker edits propagate into canonical public projection",async()=>{
 const repo=new MemoryRepository(), routed=createApp({repo}), session=store.sessions.find(s=>s.id==="ses-analytical")!;
 await routed.request(`/api/events/${EVENT_ID}/content/sessions/${session.id}`,{method:"PATCH",headers:h("org-swyx"),body:JSON.stringify({title:"Canonical edited title",abstract:"Canonical edited abstract",contentStatus:"approved"})});
 await routed.request(`/api/events/${EVENT_ID}/content/speakers/${session.speakerId}`,{method:"PATCH",headers:h("org-swyx"),body:JSON.stringify({bio:"Canonical edited bio",company:"Edited Co"})});
 const schedule=await repo.getSchedule(EVENT_ID), publicView=buildPublicProgram(schedule!);
 assert.equal(publicView.sessions.find(s=>s.id===session.id)?.title,"Canonical edited title");assert.equal(publicView.sessions.find(s=>s.id===session.id)?.abstract,"Canonical edited abstract");assert.equal(publicView.speakers.find(s=>s.id===session.speakerId)?.bio,"Canonical edited bio");
 const other=schedule!.sessions.find(s=>s.id==="ses-sam");if(other){other.publishStatus="published";await repo.putSchedule(EVENT_ID,schedule!);await routed.request(`/api/events/${EVENT_ID}/content/sessions/${other.id}`,{method:"PATCH",headers:h("org-swyx"),body:JSON.stringify({contentStatus:"draft"})});const gated=buildPublicProgram((await repo.getSchedule(EVENT_ID))!);assert.ok(!gated.sessions.some(s=>s.id===other.id));}
});

test("content state survives lifecycle snapshot roundtrip",async()=>{let snapshot:CompetitionSnapshot|undefined;const persistence:SnapshotPersistence={save:async s=>{snapshot=structuredClone(s)},load:async()=>snapshot};const isolated=createApp({persistence});const made=await isolated.request(`/api/events/${EVENT_ID}/content/tasks`,{method:"POST",headers:h("org-swyx"),body:JSON.stringify({name:"Snapshot task",dueAt:"2027-05-01T00:00:00Z",speakerIds:["spk-ada"],acceptedTypes:["application/pdf"]})});assert.equal(made.status,201);store.deliverableTasks=store.deliverableTasks.filter(t=>t.name!=="Snapshot task");await restoreSnapshot({repo:new MemoryRepository(),persistence});assert.ok(store.deliverableTasks.some(t=>t.name==="Snapshot task"))});

test("content export is a real ZIP of current versions grouped by session",async()=>{const response=await app.request(`/api/events/${EVENT_ID}/content/export`,{headers:h("org-swyx")});assert.equal(response.status,200);assert.match(response.headers.get("content-type")||"",/application\/zip/);const b=new Uint8Array(await response.arrayBuffer()),view=new DataView(b.buffer),names:string[]=[];let p=0;while(p+30<b.length&&view.getUint32(p,true)===0x04034b50){const size=view.getUint32(p+18,true),nameLen=view.getUint16(p+26,true),extra=view.getUint16(p+28,true);names.push(new TextDecoder().decode(b.slice(p+30,p+30+nameLen)));p+=30+nameLen+extra+size}assert.ok(names.length>0);assert.ok(names.every(x=>x.includes("/")));for(const f of store.contentFiles){const v=f.versions.find(x=>x.current);if(v)assert.ok(names.some(x=>x.endsWith(`/${v.name}`)))}});
