import assert from "node:assert/strict";
import test from "node:test";
import { createApp, restoreSnapshot } from "../src/app.js";
import { backfillSubmissionCodes, EVENT_ID, type LifecycleStore } from "../src/lifecycle.js";
import { buildIcs, buildPublicProgram } from "../src/publicProjection.js";
import { demoSchedule, MemoryRepository } from "../src/repository.js";
import { validateSlot } from "../src/schedule.js";
import type { CompetitionSnapshot, SnapshotPersistence } from "../src/persistence.js";

const org={"content-type":"application/json","x-demo-persona":"org-swyx"};
const post=(app:ReturnType<typeof createApp>,path:string,body:unknown={},headers=org)=>app.request(path,{method:"POST",headers,body:JSON.stringify(body)});

test("new CFP submissions receive stable sequential event-local codes exposed by APIs",async()=>{
 const app=createApp({repo:new MemoryRepository()}),email=`codes-${crypto.randomUUID()}@example.test`;
 const made=await post(app,"/api/public/events/ai-engineer-summit/submissions",{name:"Code Speaker",email,answers:{title:"Code Talk",abstract:"A sufficiently descriptive abstract for the coded submission.",category:"AI Engineering",format:"Talk (30 min)",experience:"Advanced"}},{"content-type":"application/json"});assert.equal(made.status,201);const madeBody=await made.json() as any,id=madeBody.data.id;assert.match(madeBody.data.code,/^SESS-\d{2,}$/);
 const detail=await app.request(`/api/events/${EVENT_ID}/submissions/${id}`,{headers:org}),body=await detail.json() as any;assert.match(body.data.code,/^SESS-\d{2,}$/);const first=body.data.code;
 const list=await app.request(`/api/events/${EVENT_ID}/submissions`,{headers:org}),listed=await list.json() as any;assert.equal(listed.data.find((x:any)=>x.id===id).code,first);
 const made2=await post(app,"/api/public/events/ai-engineer-summit/submissions",{name:"Second Code Speaker",email:`codes-2-${crypto.randomUUID()}@example.test`,answers:{title:"Second Code Talk",abstract:"A second sufficiently descriptive abstract for sequential codes.",category:"AI Engineering",format:"Talk (30 min)",experience:"Advanced"}},{"content-type":"application/json"}),madeBody2=await made2.json() as any;assert.equal(Number(madeBody2.data.code.slice(5)),Number(first.slice(5))+1);
});

test("seeded submission codes are present and unique",async()=>{const {store}=await import("../src/lifecycle.js"),codes=store.submissions.map(x=>x.code);assert.equal(codes.every(x=>/^SESS-\d{2,}$/.test(x||"")),true);assert.equal(new Set(codes).size,codes.length)});

test("snapshot restore preserves existing codes and deterministically backfills missing codes after max",async()=>{
 const lifecycle=await import("../src/lifecycle.js"),original=structuredClone(lifecycle.store),base=structuredClone(lifecycle.store) as LifecycleStore;base.submissions=[
  {...base.submissions[0],id:"sub-z",code:undefined,createdAt:"2026-01-02T00:00:00Z"},
  {...base.submissions[0],id:"sub-existing",code:"SESS-07",createdAt:"2026-01-03T00:00:00Z"},
  {...base.submissions[0],id:"sub-a",code:undefined,createdAt:"2026-01-02T00:00:00Z"},
 ];
 let saved:CompetitionSnapshot={version:1,eventId:EVENT_ID,savedAt:new Date().toISOString(),lifecycle:base,schedule:structuredClone(demoSchedule),sync:{links:[],runs:[],items:[]}};const persistence:SnapshotPersistence={load:async()=>structuredClone(saved),save:async s=>{saved=structuredClone(s)}};
 try{assert.equal(await restoreSnapshot({repo:new MemoryRepository(),persistence}),true);const {store}=lifecycle;assert.equal(store.submissions.find(x=>x.id==="sub-existing")?.code,"SESS-07");assert.equal(store.submissions.find(x=>x.id==="sub-a")?.code,"SESS-08");assert.equal(store.submissions.find(x=>x.id==="sub-z")?.code,"SESS-09");backfillSubmissionCodes(store);assert.equal(store.submissions.find(x=>x.id==="sub-a")?.code,"SESS-08")}finally{for(const key of Object.keys(original) as (keyof LifecycleStore)[])(lifecycle.store as any)[key]=structuredClone(original[key])}
});

test("cancelled sessions leave public program and ICS, free conflicts, and uncancel restores conflicts",async()=>{
 const repo=new MemoryRepository(),app=createApp({repo}),path=`/api/events/${EVENT_ID}/sessions/ses-analytical`;
 const cancelled=await post(app,`${path}/cancel`,{reason:"Speaker unavailable"});assert.equal(cancelled.status,200);const cancelledBody=await cancelled.json() as any;assert.equal(cancelledBody.data.cancelled,true);assert.equal(cancelledBody.data.cancellationReason,"Speaker unavailable");
 let schedule=(await repo.getSchedule(EVENT_ID))!;let program=buildPublicProgram(schedule);assert.equal(program.sessions.some(x=>x.id==="ses-analytical"),false);assert.equal(buildIcs(program).includes("ses-analytical"),false);
 const feed=await app.request("/e/ai-engineer-summit/public/feed.json"),feedBody=await feed.json() as any;assert.equal(feedBody.sessions.some((x:any)=>x.id==="ses-analytical"),false);const ics=await app.request("/e/ai-engineer-summit/public/ics");assert.equal((await ics.text()).includes("ses-analytical"),false);
 const candidate={id:"replacement",sessionId:"ses-reliable-agents",roomId:"room-main",startsAt:"2026-10-12T17:00:00.000Z",endsAt:"2026-10-12T17:45:00.000Z"};assert.equal(validateSlot(schedule,candidate).conflicts.some(x=>x.code==="ROOM_OVERLAP"),false);
 assert.equal((await post(app,`${path}/uncancel`)).status,200);schedule=(await repo.getSchedule(EVENT_ID))!;assert.equal(validateSlot(schedule,candidate).conflicts.some(x=>x.code==="ROOM_OVERLAP"),true);
});

test("publication approval filters public output; manual sessions default draft and endpoints toggle state",async()=>{
 const repo=new MemoryRepository(),app=createApp({repo});let schedule=(await repo.getSchedule(EVENT_ID))!;assert.equal(schedule.sessions.find(x=>x.id==="ses-analytical")?.publicationState,undefined,"raw legacy seed has no explicit field before normalization");
 const listed=await app.request(`/api/events/${EVENT_ID}/schedule`,{headers:org}),listedBody=await listed.json() as any;assert.equal(listedBody.sessions.find((x:any)=>x.id==="ses-analytical").publicationState,"approved");assert.ok(listedBody.meta.publication.approved>0);
 const made=await post(app,`/api/events/${EVENT_ID}/schedule/sessions`,{title:"Manual Draft",abstract:"Draft",speakerIds:["spk-ada"],trackId:"track-infra",durationMinutes:45}),madeBody=await made.json() as any;assert.equal(made.status,201);assert.equal(madeBody.data.publicationState,"draft");
 const id=madeBody.data.id;schedule=(await repo.getSchedule(EVENT_ID))!;const manual=schedule.sessions.find(x=>x.id===id)!;manual.publishStatus="published";manual.status="published";schedule.slots.push({id:`slot-${id}`,sessionId:id,roomId:"room-main",startsAt:"2026-10-14T22:00:00.000Z",endsAt:"2026-10-14T22:45:00.000Z"});await repo.putSchedule(EVENT_ID,schedule);assert.equal(buildPublicProgram(schedule).sessions.some(x=>x.id===id),false);
 assert.equal((await post(app,`/api/events/${EVENT_ID}/sessions/${id}/approve`)).status,200);schedule=(await repo.getSchedule(EVENT_ID))!;assert.equal(buildPublicProgram(schedule).sessions.some(x=>x.id===id),true);
 assert.equal((await post(app,`/api/events/${EVENT_ID}/sessions/${id}/unapprove`)).status,200);schedule=(await repo.getSchedule(EVENT_ID))!;assert.equal(buildPublicProgram(schedule).sessions.some(x=>x.id===id),false);
});

test("organizer sessions list merges canonical CFP/manual sources, placements, speakers, and counts",async()=>{
 const repo=new MemoryRepository(),app=createApp({repo}),created=await post(app,`/api/events/${EVENT_ID}/schedule/sessions`,{title:"List API Manual",abstract:"Manual session",speakerIds:["spk-ada"],trackId:"track-infra",durationMinutes:45}),manual=await created.json() as any;assert.equal(created.status,201);
 let schedule=(await repo.getSchedule(EVENT_ID))!;schedule.slots.push({id:`slot-${manual.data.id}`,sessionId:manual.data.id,roomId:"room-main",startsAt:"2026-10-14T23:00:00.000Z",endsAt:"2026-10-14T23:45:00.000Z"});await repo.putSchedule(EVENT_ID,schedule);
 assert.equal((await app.request(`/api/events/${EVENT_ID}/sessions`,{headers:{"x-demo-persona":"rev-ada"}})).status,403);
 const response=await app.request(`/api/events/${EVENT_ID}/sessions`,{headers:org}),body=await response.json() as any;assert.equal(response.status,200);const cfp=body.data.find((x:any)=>x.id==="ses-analytical"),row=body.data.find((x:any)=>x.id===manual.data.id);assert.equal(cfp.source,"cfp");assert.match(cfp.code,/^SESS-/);assert.equal(row.source,"manual");assert.equal(row.code,null);assert.equal(row.schedule.roomId,"room-main");assert.deepEqual(row.speakers,[{id:"spk-ada",name:"Ada Lovelace"}]);assert.equal(body.summary.total,body.data.length);assert.equal(body.summary.scheduled,body.data.filter((x:any)=>x.schedule).length);assert.equal(body.summary.published,body.data.filter((x:any)=>x.publishStatus==="published").length);
});

test("embed preference PATCH persists and rejects unsafe custom CSS",async()=>{let saved:any;const persistence:SnapshotPersistence={load:async()=>saved,save:async x=>{saved=structuredClone(x)}};const app=createApp({repo:new MemoryRepository(),persistence}),made=await post(app,`/api/events/${EVENT_ID}/embed-configs`,{name:"Prefs",widget:"sessions"}),row=await made.json() as any;assert.equal(row.data.enabled,true);assert.equal(row.data.snippetFormat,"iframe");const patch=(body:any)=>app.request(`/api/events/${EVENT_ID}/embed-configs/${row.data.id}`,{method:"PATCH",headers:org,body:JSON.stringify(body)});let response=await patch({name:" Updated ",filters:{track:"agents"},theme:{accent:"#123456"},fields:{room:false},enabled:false,snippetFormat:"script",customCss:"  .card { color: red; }  "}),body=await response.json() as any;assert.equal(response.status,200);assert.equal(body.data.name,"Updated");assert.equal(body.data.enabled,false);assert.equal(body.data.snippetFormat,"script");assert.equal(body.data.customCss,".card { color: red; }");assert.equal((await patch({snippetFormat:"html"})).status,400);assert.equal((await patch({customCss:"x<ScRiPt>bad"})).status,400);assert.equal((await patch({customCss:"x</StYlE>"})).status,400);assert.equal((await patch({customCss:"x".repeat(2001)})).status,400);assert.equal(saved.lifecycle.embedConfigs.find((x:any)=>x.id===row.data.id).customCss,".card { color: red; }")});

test("speaker confirmation setting controls accepted handoff confirmation task",async()=>{const lifecycle=await import("../src/lifecycle.js"),original=structuredClone(lifecycle.store);try{const app=createApp({repo:new MemoryRepository()}),candidate=lifecycle.store.submissions.find(x=>x.status!=="accepted")!;await app.request(`/api/events/${EVENT_ID}/settings`,{method:"PUT",headers:org,body:JSON.stringify({speakerConfirmation:false})});let response=await post(app,`/api/events/${EVENT_ID}/submissions/${candidate.id}/decision`,{nextStatus:"accepted",sendComms:false}),body=await response.json() as any;assert.equal(response.status,200);assert.equal(body.data.tasks.find((x:any)=>x.type==="confirmation").status,"completed");const second=lifecycle.store.submissions.find(x=>x.status!=="accepted")!;await app.request(`/api/events/${EVENT_ID}/settings`,{method:"PUT",headers:org,body:JSON.stringify({speakerConfirmation:true})});response=await post(app,`/api/events/${EVENT_ID}/submissions/${second.id}/decision`,{nextStatus:"accepted",sendComms:false});body=await response.json() as any;assert.equal(body.data.tasks.find((x:any)=>x.type==="confirmation").status,"not_started")}finally{for(const key of Object.keys(original) as (keyof LifecycleStore)[])(lifecycle.store as any)[key]=structuredClone(original[key])}});

test("lifecycle checklist derives progress and sessions-list exposes operational states",async()=>{const lifecycle=await import("../src/lifecycle.js"),original=structuredClone(lifecycle.store);try{const repo=new MemoryRepository(),app=createApp({repo});assert.equal((await app.request(`/api/events/${EVENT_ID}/lifecycle`,{headers:{"x-demo-persona":"rev-ada"}})).status,403);let response=await app.request(`/api/events/${EVENT_ID}/lifecycle`,{headers:org}),body=await response.json() as any;assert.equal(response.status,200);assert.equal(body.data.find((x:any)=>x.id==="setup").detail,`${demoSchedule.rooms.length} rooms, ${demoSchedule.tracks.length} tracks`);assert.equal(body.data.find((x:any)=>x.id==="evaluate").done,lifecycle.store.reviewRounds.length>0&&lifecycle.store.reviewAssignments.length>0);assert.equal(body.data.find((x:any)=>x.id==="publish").done,true);await post(app,`/api/events/${EVENT_ID}/sessions/ses-analytical/cancel`,{reason:"test"});response=await app.request(`/api/events/${EVENT_ID}/sessions-list`,{headers:org});body=await response.json() as any;const cfp=body.data.find((x:any)=>x.id==="ses-analytical");assert.match(cfp.code,/^SESS-/);assert.equal(cfp.source,"cfp");assert.equal(cfp.cancelled,true);assert.equal(cfp.publicationState,"approved");assert.equal(body.meta.cancelled,body.data.filter((x:any)=>x.cancelled).length);assert.equal(body.meta.approved,body.data.filter((x:any)=>x.publicationState==="approved").length)}finally{for(const key of Object.keys(original) as (keyof LifecycleStore)[])(lifecycle.store as any)[key]=structuredClone(original[key])}});
