import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { Badge, Button, Card, Field, Input, PageHeader, Select } from "../components/ui";

function useData(load: () => Promise<any>) { const [data,setData]=useState<any[]>([]); const [error,setError]=useState(""); const reload=()=>load().then(r=>setData(r.data)).catch(e=>setError(e.message)); useEffect(()=>{ void reload(); },[]); return {data,error,reload}; }
export function EvaluationPlanPage() {
  const {data:rounds,error,reload}=useData(api.reviewRounds); const [name,setName]=useState("");
  return <div><PageHeader title="Evaluation Plan" description="Independent review rounds, dates, blind settings, reviewer pools, and weighted scorecards." actions={<Button onClick={async()=>{if(!name)return; await api.createReviewRound({name,status:"draft",blind:false,reviewerIds:[],criteria:[{id:"rating",label:"Overall rating",type:"rating",weight:1},{id:"recommendation",label:"Recommendation",type:"select",weight:0,options:["Accept","Reject"]},{id:"comments",label:"Comments",type:"text",weight:0}]});setName("");reload();}}>Add round</Button>}/>{error&&<p>{error}</p>}<div className="mb-4 max-w-sm"><Field label="New round name"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Committee Decision" /></Field></div><div className="space-y-3">{rounds.map((r:any)=><Card className="p-5" key={r.id}><div className="flex justify-between"><div><h2 className="font-bold text-lg">{r.name}</h2><p className="text-sm text-mid">{new Date(r.opensAt).toLocaleDateString()} – {new Date(r.closesAt).toLocaleDateString()}</p></div><div className="flex gap-2"><Badge>{r.status}</Badge>{r.blind&&<Badge tone="primary">Blind</Badge>}</div></div><p className="mt-3 text-xs font-bold uppercase text-mid">Scorecard criteria</p><div className="mt-2 flex flex-wrap gap-2">{r.criteria.map((c:any)=><Badge key={c.id}>{c.label} · {c.type}{c.weight?` · ${c.weight}×`:""}</Badge>)}</div><p className="mt-3 text-sm">Reviewer pool: {r.reviewerIds.join(", ")||"Not configured"}</p></Card>)}</div></div>;
}
export function AssignmentsPage() {
 const {data:rounds}=useData(api.reviewRounds); const {data:subs}=useData(api.submissions); const [roundId,setRound]=useState("round-initial"),[reviewerId,setReviewer]=useState("rev-ada"),[cap,setCap]=useState(5),[message,setMessage]=useState("");
 const run=async(method:string)=>{const r=await api.assignReviews({roundId,reviewerId,submissionIds:subs.map((s:any)=>s.id),method,cap});setMessage(`${r.data.length} assignments created`)};
 return <div><PageHeader title="Assignments" description="Assign specific abstracts or auto-distribute the queue with a per-reviewer cap."/><Card className="grid gap-4 p-5 md:grid-cols-3"><Field label="Round"><Select value={roundId} onChange={e=>setRound(e.target.value)}>{rounds.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></Field><Field label="Reviewer"><Select value={reviewerId} onChange={e=>setReviewer(e.target.value)}><option value="rev-ada">Ada Reviewer</option><option value="rev-linus">Linus Reviewer</option></Select></Field><Field label="Per-reviewer limit"><Input type="number" min={1} value={cap} onChange={e=>setCap(Number(e.target.value))}/></Field><div className="flex gap-2"><Button onClick={()=>run("specific")}>Assign selected</Button><Button variant="outline" onClick={()=>run("auto")}>Auto-distribute</Button></div>{message&&<p className="text-sm font-semibold text-ink">{message}</p>}</Card></div>;
}
export function ReviewProgressPage() { const {data, reload}=useData(api.reviewProgress); const [message,setMessage]=useState(""); const outstanding=data.filter((r:any)=>r.outstanding).map((r:any)=>r.reviewerId); return <div><PageHeader title="Review Progress" description="Live completion by round and reviewer." actions={<Button disabled={!outstanding.length} onClick={async()=>{const r=await api.reviewReminders([...new Set(outstanding)]);setMessage(`${r.data.length} reminder(s) logged and sent via the configured mailer`);reload();}}>Remind outstanding reviewers</Button>}/>{message&&<p className="mb-3 text-sm text-ink">{message}</p>}<div className="space-y-2">{data.map((r:any)=><Card className="flex items-center justify-between p-4" key={`${r.roundId}-${r.reviewerId}`}><div><b>{r.reviewer?.name||r.reviewerId}</b><p className="text-xs text-mid">{r.roundName}</p></div><div className="text-right"><b>{r.completed} of {r.assigned} complete · {r.percent}%</b><p className="text-xs text-mid">{r.outstanding} outstanding</p></div></Card>)}</div></div>; }
export function ResultsPage() { const {data}=useData(api.reviewResults); const [desc,setDesc]=useState(true); const rows=[...data].sort((a,b)=>(Number(b.aggregateScore||0)-Number(a.aggregateScore||0))*(desc?1:-1)); return <div><PageHeader title="Results" description="Human review aggregates, recommendations, and disposition. AI drafts remain advisory." actions={<><Button variant="outline" onClick={()=>setDesc(!desc)}>Sort score {desc?"high → low":"low → high"}</Button><Button onClick={()=>window.location.assign(api.reviewResultsCsv())}>Export CSV</Button></>}/><div className="overflow-x-auto rounded-[24px] border bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Submission</th><th>Score</th><th>Reviews</th><th>Recommendations</th><th>Status</th></tr></thead><tbody>{rows.map((r:any)=><tr className="border-b" key={r.id}><td className="p-3"><b>{r.title}</b><div className="text-xs text-mid">{r.name} · {r.company||r.answers?.company||"Independent"}</div></td><td>{r.aggregateScore?.toFixed(2)||"—"}</td><td>{r.reviewerCount}</td><td>{Object.entries(r.recommendationCounts||{}).map(([k,v])=>`${k}: ${v}`).join(", ")||"—"}</td><td><Badge>{r.status}</Badge></td></tr>)}</tbody></table></div></div>; }
