import { Hono } from "hono";
import { EVENT_ID, type ContentApprovalStatus, type LifecycleStore } from "./lifecycle.js";
import type { Mailer } from "./mailer.js";
import type { Repository } from "./domain.js";
import { addFileVersion, canAccessFile, contentReadiness, validateUpload } from "./content.js";
import { createZip } from "./zip.js";

const fail=(c:any,message:string,status=400)=>c.json({error:{message}},status as any);
const validStatus=(v:string):v is ContentApprovalStatus=>["draft","submitted","approved","changes_requested"].includes(v);
export function createContentRoutes(deps:{store:LifecycleStore;persist:()=>Promise<void>;persona:(c:any)=>{id:string;role:string;name:string;email:string;speakerId?:string};mailer:Mailer;repo:Repository}) {
 const app=new Hono(); const event=(c:any)=>c.req.param("eventId")===EVENT_ID; const org=(c:any)=>deps.persona(c).role==="organizer";
 const scheduleRepo=deps.repo as Repository&{getSchedule?:(id:string)=>Promise<any>;putSchedule?:(id:string,s:any)=>Promise<void>};
 /**
  * Mirror a lifecycle session edit onto the canonical schedule session that every
  * public widget/feed reads.
  *
  * Publication rule: approving content PUBLISHES the session; any other content
  * status LEAVES the existing publication state alone. Previously this line reset
  * publishStatus to "draft" on every edit, which silently UNPUBLISHED a live
  * session the moment an organizer fixed its title — the edit then never reached
  * the public catalog.
  */
 const syncSession=async(sessionId:string)=>{const life=deps.store.sessions.find(s=>s.id===sessionId), state=deps.store.sessionContent.find(s=>s.sessionId===sessionId), schedule=await scheduleRepo.getSchedule?.(EVENT_ID), target=schedule?.sessions.find((s:any)=>s.id===sessionId);if(life&&target){target.title=life.title;target.abstract=life.abstract;target.trackIds=[life.trackId];target.format=(life as any).format||target.format;if(state?.status==="approved"){target.publishStatus="published";if(target.status!=="published")target.status=target.status||"accepted";}else if(state?.status==="changes_requested"){target.publishStatus="draft";}if(scheduleRepo.putSchedule)await scheduleRepo.putSchedule(EVENT_ID,schedule);}};
 const syncSpeaker=async(speakerId:string)=>{const profile=deps.store.profiles.find(p=>p.speakerId===speakerId), schedule=await scheduleRepo.getSchedule?.(EVENT_ID), target=schedule?.speakers.find((s:any)=>s.id===speakerId);if(profile&&target){Object.assign(target,{name:profile.name,bio:profile.bio,company:profile.company,title:profile.title,headshotUrl:(profile as any).headshotUrl});if(scheduleRepo.putSchedule)await scheduleRepo.putSchedule(EVENT_ID,schedule);}};
 app.get("/api/events/:eventId/content",(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);return c.json({data:{tasks:contentReadiness(deps.store),files:deps.store.contentFiles.map(f=>({...f,speaker:deps.store.profiles.find(p=>p.speakerId===f.speakerId),session:deps.store.sessions.find(s=>s.id===f.sessionId),currentVersion:f.versions.find(v=>v.current)})),sessions:deps.store.sessions.map(s=>({...s,contentStatus:deps.store.sessionContent.find(x=>x.sessionId===s.id)?.status||"draft"})),speakers:deps.store.profiles}})});
 app.post("/api/events/:eventId/content/tasks",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const b=await c.req.json();if(!b.name||!b.dueAt||!Array.isArray(b.speakerIds)||!b.speakerIds.length)return fail(c,"name, due date, and assigned speakers are required");const made=b.speakerIds.flatMap((speakerId:string)=>{const sessions=(b.sessionIds?.length?deps.store.sessions.filter(s=>b.sessionIds.includes(s.id)&&s.speakerId===speakerId):deps.store.sessions.filter(s=>s.speakerId===speakerId));const targets=sessions.length?sessions:[undefined];return targets.map((session:any)=>({id:`deliverable-${crypto.randomUUID().slice(0,8)}`,name:b.name,instructions:b.instructions||"",dueAt:b.dueAt,speakerId,sessionId:session?.id,fileRequired:b.fileRequired!==false,acceptedTypes:b.acceptedTypes||["application/pdf"],status:"incomplete" as const,createdAt:new Date().toISOString()}));});deps.store.deliverableTasks.push(...made);await deps.persist();return c.json({data:made},201)});
 app.get("/api/speaker/events/:eventId/deliverables",(c)=>{if(!event(c))return fail(c,"event not found",404);const p=deps.persona(c);if(p.role!=="speaker"||!p.speakerId)return fail(c,"speaker role required",403);return c.json({data:contentReadiness(deps.store).filter(t=>t.speakerId===p.speakerId)})});
 app.get("/api/speaker/events/:eventId/deliverables/:taskId",(c)=>{if(!event(c))return fail(c,"event not found",404);const p=deps.persona(c),task=deps.store.deliverableTasks.find(t=>t.id===c.req.param("taskId"));if(!task||p.role!=="speaker"||task.speakerId!==p.speakerId)return fail(c,"deliverable not found",404);const file=deps.store.contentFiles.find(f=>f.taskId===task.id);return c.json({data:{...contentReadiness(deps.store).find(t=>t.id===task.id),file}})});
 app.post("/api/speaker/events/:eventId/deliverables/:taskId/upload",async(c)=>{if(!event(c))return fail(c,"event not found",404);const p=deps.persona(c),task=deps.store.deliverableTasks.find(t=>t.id===c.req.param("taskId"));if(!task||p.role!=="speaker"||task.speakerId!==p.speakerId)return fail(c,"deliverable not found",404);const b=await c.req.json();const check=validateUpload(b,task.acceptedTypes);if(!check.ok)return fail(c,check.error);const made=addFileVersion(deps.store,{task,name:b.name,mime:b.mime,size:b.size,dataBase64:b.dataBase64,uploadedBy:p.id,kind:b.kind||"document"});await deps.persist();return c.json({data:made},201)});
 app.get("/api/content/files/:fileId/versions/:versionId",(c)=>{const p=deps.persona(c),file=deps.store.contentFiles.find(f=>f.id===c.req.param("fileId"));if(!file||!canAccessFile(file,p))return fail(c,"file not found",404);const version=file.versions.find(v=>v.id===c.req.param("versionId"));if(!version)return fail(c,"version not found",404);const bytes=Uint8Array.from(atob(version.dataBase64),x=>x.charCodeAt(0));return c.body(bytes.buffer,200,{"content-type":version.mime,"content-disposition":`inline; filename="${version.name.replaceAll('"','')}"`})});
 app.post("/api/content/files/:fileId/comments",async(c)=>{const p=deps.persona(c),file=deps.store.contentFiles.find(f=>f.id===c.req.param("fileId"));if(!file||!canAccessFile(file,p))return fail(c,"file not found",404);const b=await c.req.json();if(!String(b.body||"").trim())return fail(c,"comment is required");const row={id:`comment-${crypto.randomUUID().slice(0,8)}`,authorId:p.id,authorName:p.name,body:String(b.body),createdAt:new Date().toISOString()};file.comments.push(row);await deps.persist();return c.json({data:row},201)});
 app.patch("/api/events/:eventId/content/files/:fileId/approval",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const file=deps.store.contentFiles.find(f=>f.id===c.req.param("fileId")),b=await c.req.json();if(!file)return fail(c,"file not found",404);if(!validStatus(b.status))return fail(c,"invalid approval status");file.status=b.status;file.approvalComment=b.comment||"";await deps.persist();return c.json({data:file})});
 app.post("/api/events/:eventId/content/reminders",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const b=await c.req.json().catch(()=>({}));const outstanding=contentReadiness(deps.store).filter(t=>t.status!=="complete"&&(!b.overdueOnly||t.overdue)),ids=[...new Set(outstanding.map(t=>t.speakerId))],sent=[];for(const speakerId of ids){const profile=deps.store.profiles.find(p=>p.speakerId===speakerId);if(!profile)continue;const names=outstanding.filter(t=>t.speakerId===speakerId).map(t=>`${t.name} (due ${t.dueAt.slice(0,10)})`);const result=await deps.mailer.send({to:profile.email,subject:"Speaker deliverables outstanding",text:`Please complete: ${names.join(", ")}`}).catch(()=>({status:"failed" as const}));deps.store.communications.push({id:`comm-${crypto.randomUUID().slice(0,8)}`,speakerId,subject:"Speaker deliverables outstanding",body:names.join("\n"),kind:"reminder",status:result.status,ics:"",createdAt:new Date().toISOString()});sent.push({speakerId,status:result.status});}await deps.persist();return c.json({data:sent})});
 app.patch("/api/events/:eventId/content/sessions/:sessionId",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const s=deps.store.sessions.find(x=>x.id===c.req.param("sessionId")),b=await c.req.json();if(!s)return fail(c,"session not found",404);const before={title:s.title,abstract:s.abstract,trackId:s.trackId,format:(s as any).format};Object.assign(s,{title:b.title??s.title,abstract:b.abstract??s.abstract,trackId:b.trackId??s.trackId});if(b.format!==undefined)(s as any).format=b.format;let state=deps.store.sessionContent.find(x=>x.sessionId===s.id);if(!state){state={sessionId:s.id,status:"draft"};deps.store.sessionContent.push(state)}if(b.contentStatus){if(!validStatus(b.contentStatus))return fail(c,"invalid approval status");state.status=b.contentStatus;state.approvalComment=b.approvalComment||""}const p=deps.persona(c);deps.store.contentHistory.push({id:`history-${crypto.randomUUID().slice(0,8)}`,entityType:"session",entityId:s.id,editorId:p.id,editorName:p.name,createdAt:new Date().toISOString(),before,after:{title:s.title,abstract:s.abstract,trackId:s.trackId,format:(s as any).format}});await syncSession(s.id);await deps.persist();return c.json({data:{...s,contentStatus:state.status,history:deps.store.contentHistory.filter(h=>h.entityId===s.id)}})});
 app.post("/api/events/:eventId/content/history/:historyId/restore",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const h=deps.store.contentHistory.find(x=>x.id===c.req.param("historyId"));if(!h)return fail(c,"history not found",404);if(h.entityType==="session"){const s=deps.store.sessions.find(x=>x.id===h.entityId);if(s){Object.assign(s,h.before);await syncSession(s.id)}}else{const p=deps.store.profiles.find(x=>x.speakerId===h.entityId);if(p){Object.assign(p,h.before);await syncSpeaker(p.speakerId)}}await deps.persist();return c.json({data:h})});
 app.patch("/api/events/:eventId/content/speakers/:speakerId",async(c)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const profile=deps.store.profiles.find(p=>p.speakerId===c.req.param("speakerId")),b=await c.req.json();if(!profile)return fail(c,"speaker not found",404);const before={bio:profile.bio,company:profile.company,title:profile.title,headshotUrl:(profile as any).headshotUrl};Object.assign(profile,{bio:b.bio??profile.bio,company:b.company??profile.company,title:b.title??profile.title});if(b.headshotUrl!==undefined)(profile as any).headshotUrl=b.headshotUrl;const p=deps.persona(c);deps.store.contentHistory.push({id:`history-${crypto.randomUUID().slice(0,8)}`,entityType:"speaker",entityId:profile.speakerId,editorId:p.id,editorName:p.name,createdAt:new Date().toISOString(),before,after:{bio:profile.bio,company:profile.company,title:profile.title,headshotUrl:(profile as any).headshotUrl}});await syncSpeaker(profile.speakerId);await deps.persist();return c.json({data:profile})});
 const exportZip=(c:any)=>{if(!event(c))return fail(c,"event not found",404);if(!org(c))return fail(c,"organizer role required",403);const clean=(s:string)=>s.replace(/[^a-zA-Z0-9._ -]+/g,"-");const entries=deps.store.contentFiles.flatMap(f=>{const v=f.versions.find(x=>x.current)||f.versions.at(-1);if(!v)return[];const session=deps.store.sessions.find(s=>s.id===f.sessionId);return[{name:`${clean(session?.title||"General")}/${clean(v.name)}`,bytes:Uint8Array.from(atob(v.dataBase64),x=>x.charCodeAt(0))}]});const zip=createZip(entries);return c.body(zip.buffer,200,{"content-type":"application/zip","content-disposition":"attachment; filename=cue-latest-content.zip","x-cue-file-count":String(entries.length)})};
 app.get("/api/events/:eventId/content/export",exportZip);app.post("/api/events/:eventId/content/export",exportZip);
 return app;
}
