import type { EntityType, Session, Speaker } from "./domain.js";
export const MAPPING_VERSION = "accelevents-v1-placeholder";
export interface Mapped { entityType: EntityType; localId: string; payload: Record<string, unknown>; warnings: string[]; payloadHash: string; idempotencyKey: string; summary: string }
const stable = (value: unknown): string => Array.isArray(value) ? `[${value.map(stable).join(",")}]` : value && typeof value === "object" ? `{${Object.entries(value as Record<string,unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([k,v]) => `${JSON.stringify(k)}:${stable(v)}`).join(",")}}` : JSON.stringify(value);
export async function hash(value: unknown): Promise<string> { const b = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(stable(value))); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("") }
async function mapped(entityType: EntityType, localId: string, payload: Record<string,unknown>, warnings: string[]): Promise<Mapped> { const payloadHash = await hash(payload); return { entityType, localId, payload, warnings, payloadHash, idempotencyKey: `accelevents:${entityType}:${localId}:${payloadHash}`, summary: JSON.stringify({ localId, fields: Object.keys(payload), warnings }).slice(0, 1000) } }
/** Placeholder Accelevents field names/paths are isolated here pending API confirmation. */
export async function mapSpeaker(s: Speaker): Promise<Mapped> { const warnings = s.email ? [] : ["missing email"]; return mapped("speaker", s.id, { external_reference: s.id, name: s.name.trim(), email: s.email.toLowerCase(), biography: s.bio.trim(), organization: s.company || null }, warnings) }
export async function mapSession(s: Session): Promise<Mapped> { const warnings = s.speakerIds.length ? [] : ["session has no speakers"]; return mapped("session", s.id, { external_reference: s.id, title: s.title.trim(), description: s.abstract.trim(), speaker_references: [...s.speakerIds].sort(), starts_at: s.startsAt, ends_at: s.endsAt, track: s.track, room: s.room }, warnings) }
